Make initial ./ optional when stripping ./.eunit/
On my system, the filenames in .eunit were being found without the
initial ./. This caused the sed expression that trims off ./.eunit/ to
not match,  and therefore leave the ./eunit. For example, when
running unit tests on the quick start guide project, I would get the
following:

beam/beam-load.c(1250): Error loading module '.eunit/unit-my-test-lib-tests'